# Generated by Django 3.1.7 on 2021-03-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210317_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo_01',
            field=models.ImageField(blank=True, null=True, upload_to='images/news'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo_02',
            field=models.ImageField(blank=True, null=True, upload_to='images/news'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo_03',
            field=models.ImageField(blank=True, null=True, upload_to='images/news'),
        ),
    ]
