# Generated by Django 3.1.7 on 2021-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_perex'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
