# Generated by Django 3.1.7 on 2021-03-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210317_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Články'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created',
            new_name='created_date',
        ),
    ]
