# Generated by Django 3.2.7 on 2021-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_rename_tag_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time_to_read',
            field=models.IntegerField(default=0),
        ),
    ]
