# Generated by Django 4.0.3 on 2022-04-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20220417_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo_01',
            field=models.ImageField(blank=True, default='images/news/AKBMX.jpg', null=True, upload_to='images/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_02',
            field=models.ImageField(blank=True, null=True, upload_to='images/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_03',
            field=models.ImageField(blank=True, null=True, upload_to='images/news'),
        ),
    ]
