# Generated by Django 4.0.4 on 2022-05-15 13:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_news_photo_01_alter_news_photo_02_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents')),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ke stažení',
                'verbose_name_plural': 'Ke stažení',
            },
        ),
    ]
