# Generated by Django 4.0.4 on 2022-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
