# Generated by Django 4.0.4 on 2022-05-15 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_alter_downloads_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Typ dokumentu',
                'verbose_name_plural': 'Typ dokumnentů',
            },
        ),
        migrations.AddField(
            model_name='downloads',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.documenttag'),
        ),
    ]
