# Generated by Django 4.0.4 on 2022-05-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_documenttag_downloads_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='tag',
        ),
        migrations.AddField(
            model_name='downloads',
            name='tag',
            field=models.ManyToManyField(to='news.documenttag'),
        ),
    ]
