# Generated by Django 4.0.4 on 2022-05-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_rename_tag_downloads_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloads',
            old_name='document',
            new_name='path',
        ),
    ]
