# Generated by Django 4.0.4 on 2022-05-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_rename_document_downloads_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='path',
        ),
    ]
