# Generated by Django 4.0.4 on 2022-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_remove_downloads_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
