# Generated by Django 4.1.2 on 2023-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_alter_news_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='prefix',
            field=models.TextField(default='', max_length=400),
        ),
    ]
