# Generated by Django 4.1.2 on 2023-02-26 17:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_alter_news_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='prefix',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=400, null=True),
        ),
    ]
