# Generated by Django 4.2.6 on 2023-10-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_alter_news_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttag',
            options={'verbose_name': 'Typ dokumentu', 'verbose_name_plural': 'Typ dokumentů'},
        ),
    ]
