# Generated by Django 5.2.7 on 2025-10-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0035_alter_documenttag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="view_count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Počet zhlédnutí"
            ),
        ),
    ]
