# Generated by Django 5.2.7 on 2025-10-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0036_news_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="media/audio/"),
        ),
    ]
