# Generated by Django 5.2.7 on 2025-10-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0037_news_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="audio_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="news",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio/news/"),
        ),
    ]
