# Generated by Django 5.2.7 on 2025-10-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0038_news_audio_hash_alter_news_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="published_audio",
            field=models.BooleanField(default=False, help_text="Audio zveřejněno"),
        ),
        migrations.AlterField(
            model_name="news",
            name="published",
            field=models.BooleanField(default=False, help_text="Článek zveřejněn"),
        ),
    ]
