# Generated by Django 5.2.7 on 2025-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_news_published_audio_alter_news_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
