# Generated by Django 6.0.3 on 2026-03-18 22:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_downloads_downloads_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automaticky generováno z titulku pro hezké URL', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30000, null=True),
        ),
    ]
