# Generated by Django 6.0.3 on 2026-05-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_news_slug_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish_in_app',
            field=models.BooleanField(default=False, help_text='Zveřejnit v mobilní aplikaci'),
        ),
    ]
