# Generated by Django 6.0.3 on 2026-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_news_multilang_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_de',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='title_it',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sk',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
