# Generated by Django 6.0.3 on 2026-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_news_title_de_news_title_en_news_title_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='audio_file_hu',
            field=models.FileField(blank=True, null=True, upload_to='audio/news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='audio_file_pl',
            field=models.FileField(blank=True, null=True, upload_to='audio/news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_hu',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='content_pl',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='prefix_hu',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='prefix_pl',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hu',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pl',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
