# Generated by Django 5.1.7 on 2025-03-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
