# Generated by Django 5.1.7 on 2025-03-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_stats', '0002_visit_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
