# Generated by Django 5.2.7 on 2025-11-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_rename_riders_on_event_club_riders_on_events'),
        ('event', '0058_rename_best_cl_seasonsettings_best_league_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('word', models.FileField(upload_to='invoices/word/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='invoices/pdf/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'verbose_name': 'Faktura za startovné',
                'verbose_name_plural': 'Faktury za startovné',
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
