# Generated by Django 6.0.3 on 2026-03-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_subscriptioninvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvoice',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventinvoice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
