# Generated by Django 6.0.3 on 2026-06-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_eventinvoice_created_and_more'),
        ('rider', '0056_mobileappsubscription_mobileappcharge_promocode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='mobile_charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='rider.mobileappcharge'),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='invoice_type',
            field=models.CharField(choices=[('rider_stats', 'Individuální předplatné'), ('trainer_club_stats', 'Klubové předplatné trenéra'), ('trainer_extended', 'Rozšířené předplatné trenéra'), ('mobile_app', 'Předplatné mobilní aplikace')], db_index=True, max_length=40),
        ),
    ]
