from django.urls import path
from . import views
from .feeds import EventFeed

app_name = 'event'

urlpatterns = [
    path('feed.ics', EventFeed(), name='feed'),
    path('', views.events_list_view, name='events'),
    path('<int:pk>', views.event_detail_views, name='event-detail'),
    path('proposition/<int:pk>', views.proposition_detail_view, name='proposition-detail'),
    path('proposition/<int:pk>/edit', views.proposition_edit_view, name='proposition-edit'),
    path('results/<int:pk>', views.results_view, name='results'),
    path('events-by-year/<int:pk>', views.events_list_by_year_view, name='events-by-year'),
    path('entry-riders/<int:pk>', views.entry_riders_view, name='entry-riders'),
    path('entry/<int:pk>', views.add_entries_view, name='entry'),
    path('entry-foreign/<int:pk>', views.entry_foreign_view, name='entry-foreign'),
    path('entry-foreign-summary/<int:pk>', views.entry_foreign_summary_view, name='entry-foreign-summary'),
    path('entry-foreign-pay/<int:pk>', views.entry_foreign_pay_view, name='entry-foreign-pay'),
    path('entry-foreign-success/<int:pk>', views.entry_foreign_success_view, name='entry-foreign-success'),
    path('confirm', views.confirm_view, name='confirm'),
    path('order', views.confirm_user_order, name='order'),
    path('success', views.check_order_payments, name="check-payments"),
    path('success/<int:pk>', views.success_view, name='success'),
    path('cancel', views.cancel_view, name='cancel'),
    path('event-admin/<int:pk>', views.event_admin_view, name='event-admin'),
    path('find-payment', views.find_payment_view, name='find-payment'),
    path('commissar-assignments/', views.commissar_assignments_view, name='commissar-assignments'),
    path('commissar-statistics/', views.commissar_statistics_view, name='commissar-statistics'),
    path('ranking-table', views.ranking_table_view, name='ranking-table'),
    path('ec_by_club_xls/<int:pk>', views.ec_by_club_xls, name='ec_by_club_xls'),
    path('summary_riders_in_event/<int:pk>', views.summary_riders_in_event, name='summary_riders_in_event'),
    path('checkout', views.checkout_view, name='checkout'),
    path('fees-on-event/<int:pk>', views.fees_on_event, name='fees-on-event'),
    path('fees-on-event/<int:pk>/invoice-edit/<int:club_id>/', views.invoice_edit_view, name='invoice-edit'),
    path('fees-on-event/<int:pk>/invoice-delete/<int:invoice_id>/', views.invoice_delete_view, name='invoice-delete'),
    path('fees-on-event/<int:pk>/cash-receipts/', views.cash_receipts_on_event, name='cash-receipts-on-event'),
    path('fees-on-event/<int:pk>/cash-receipts/export/', views.cash_receipts_export_view, name='cash-receipts-export'),
    path('fees-on-event/<int:pk>/cash-receipts/<int:receipt_id>/pdf/', views.cash_receipt_pdf_view, name='cash-receipt-pdf'),
    path('fees-on-event/<int:pk>/cash-receipts/<int:receipt_id>/edit/', views.cash_receipt_edit_view, name='cash-receipt-edit'),
    path('fees-on-event/<int:pk>/cash-receipts/<int:receipt_id>/delete/', views.cash_receipt_delete_view, name='cash-receipt-delete'),
    path('credit', views.credit_view, name='credit'),
    path("stripe-credit-webhook/", views.stripe_credit_webhook, name="stripe-credit-webhook"),
    path('success-credit', views.success_credit_view, name='success-credit'),
    path('success-credit-update', views.success_credit_update_view, name='success-credit-update'),
    path('not-reg', views.not_reg_view, name='not-reg'),
    path('check-rider/', views.check_rider, name='check-rider'),
    path('generate_pdf/<int:pk>', views.generate_pdf, name='generate_pdf'),
    path('generate_invoice_preparation_pdf/<int:pk>', views.generate_invoice_preparation_pdf, name='generate_invoice_preparation_pdf'),
    path('generate_invoices_pdf/<int:pk>', views.invoice_view, name='generate_invoices_pdf'),
    path('invalid-licences-pdf/<int:pk>', views.invalid_licences_pdf, name='invalid-licences-pdf'),
    path('price-money/<int:pk>', views.price_money_pdf, name='price-money-pdf'),
    path('recalculate_balances_view', views.recalculate_balances_view, name='recalculate_balances_view'),
    path('import-stats/<int:pk>', views.import_event_stats, name='import-stats'),
    path("export-results/<int:event_id>/", views.export_event_results, name="export_event_results"),
]
