# Generated by Django 3.2 on 2021-04-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/users/uni.jpeg', null=True, upload_to='static/images/users/'),
        ),
    ]
