# Generated by Django 5.0.3 on 2025-02-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="account", name="credit", field=models.IntegerField(default=0),
        ),
    ]
