# Generated by Django 3.2.12 on 2022-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210417_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/users/blank-avatar-200x200.jpg', null=True, upload_to='static/images/users/'),
        ),
    ]
