# Generated by Django 4.0.3 on 2022-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='images/users/blank-avatar-200x200.jpg', null=True, upload_to='images/users/'),
        ),
    ]
