# Generated by Django 5.0.3 on 2025-02-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_account_credit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account", old_name="credit", new_name="user_credit",
        ),
    ]
