# Generated by Django 6.0.3 on 2026-03-23 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_is_trainer_account_trainer_clubs'),
        ('rider', '0053_alter_riderstatscharge_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRiderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_links', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='rider.rider')),
            ],
            options={
                'verbose_name': 'Vazba uživatel-jezdec',
                'verbose_name_plural': 'Vazby uživatel-jezdec',
                'ordering': ['account__last_name', 'account__first_name', 'rider__last_name', 'rider__first_name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='riders',
            field=models.ManyToManyField(blank=True, related_name='linked_accounts', through='accounts.AccountRiderLink', to='rider.rider'),
        ),
        migrations.AddConstraint(
            model_name='accountriderlink',
            constraint=models.UniqueConstraint(fields=('account', 'rider'), name='unique_account_rider_link'),
        ),
    ]
