# Generated by Django 6.0.3 on 2026-03-23 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_accountriderlink_account_riders_and_more'),
        ('rider', '0053_alter_riderstatscharge_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/avatar-change-requests/')),
                ('status', models.CharField(choices=[('pending', 'Čeká na schválení'), ('approved', 'Schváleno'), ('rejected', 'Zamítnuto')], db_index=True, default='pending', max_length=20)),
                ('review_note', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_avatar_change_requests', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_change_requests', to=settings.AUTH_USER_MODEL)),
                ('target_rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_change_requests', to='rider.rider')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_avatar_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Žádost o změnu avataru',
                'verbose_name_plural': 'Žádosti o změnu avataru',
                'ordering': ['-created'],
            },
        ),
    ]
