# Generated by Django 6.0.3 on 2026-04-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_accountactivationauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingActivationAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Čekající aktivace účtu',
                'verbose_name_plural': 'Čekající aktivace účtů',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.account',),
        ),
    ]
