# Generated by Django 3.1.7 on 2021-03-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('ranking_code', models.IntegerField(default=0)),
                ('registration_open', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='club.club')),
            ],
        ),
    ]
