# Generated by Django 4.0.3 on 2022-04-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0006_auto_20211003_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='', max_length=255)),
                ('event', models.IntegerField(blank=True, default=0, null=True)),
                ('rider', models.IntegerField(default=0)),
                ('is_20', models.BooleanField(default=False)),
                ('is_24', models.BooleanField(default=False)),
                ('class_20', models.CharField(default='', max_length=255)),
                ('class_24', models.CharField(default='', max_length=255)),
                ('fee_20', models.IntegerField(blank=True, default=0, null=True)),
                ('fee_24', models.IntegerField(blank=True, default=0, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_complete', models.BooleanField(default=False)),
                ('logout', models.BooleanField(default=False)),
                ('date_of_payment', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Mistrovství ČR jednotlivců', 'Mistrovství ČR jednotlivců'), ('Mistrovství ČR družstev', 'Mistrovství ČR družstev'), ('Český pohár', 'Český pohár'), ('Česká liga', 'Česká liga'), ('Moravská liga', 'Moravská liga'), ('Volný závod', 'Volný závod'), ('Nebodovaný závod', 'Nebodovaný závod'), ('Mezinárodní závod', 'Mezinárodní závod')], default='Volný závod', max_length=100)),
                ('classes_code', models.IntegerField(default=3)),
                ('event_classes', models.IntegerField(default=0)),
                ('is_uci_race', models.BooleanField(default=False)),
                ('pcp', models.CharField(blank=True, max_length=255, null=True)),
                ('pcp_assist', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_open_from', models.DateField(default='2021-04-01')),
                ('reg_open_to', models.DateField(default='2021-12-31')),
                ('reg_open', models.BooleanField(default=True)),
                ('system', models.CharField(blank=True, choices=[('3 základní rozjíždky a KO system', '3 základní rozjíždky a KO system'), ('5 základních rozjíždek a KO system', '5 základních rozjíždek a KO system')], default='3 základní rozjíždky a KO system', max_length=100, null=True)),
                ('prices', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('timeschedule', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('bem_entries', models.FileField(blank=True, null=True, upload_to='static/bem_entries')),
                ('bem_entries_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('bem_riders_list', models.FileField(blank=True, null=True, upload_to='static/bem_riders')),
                ('bem_riders_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('full_results_path', models.FileField(blank=True, null=True, upload_to='static/full_results')),
                ('full_results_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('results_path_to_file', models.FileField(blank=True, null=True, upload_to='static/results')),
                ('results_uploaded', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='club.club')),
            ],
            options={
                'verbose_name': 'Závod',
                'verbose_name_plural': 'Závody',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('organizer', models.CharField(blank=True, max_length=100, null=True)),
                ('rider', models.IntegerField(default=0)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('club', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('is_20', models.BooleanField(default=1)),
                ('marked_20', models.BooleanField(default=0)),
                ('marked_24', models.BooleanField(default=0)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event')),
            ],
            options={
                'verbose_name': 'Výsledek',
                'verbose_name_plural': 'Výsledky',
            },
        ),
    ]
