# Generated by Django 4.0.4 on 2022-05-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='EntryForeign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='', max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('uci_id', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=3)),
                ('club', models.CharField(max_length=50)),
                ('transponder', models.CharField(max_length=10)),
                ('is_20', models.BooleanField(default=False)),
                ('is_24', models.BooleanField(default=False)),
                ('class_20', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('class_24', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fee_20', models.IntegerField(blank=True, default=0, null=True)),
                ('fee_24', models.IntegerField(blank=True, default=0, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_complete', models.BooleanField(default=False)),
                ('checkout', models.BooleanField(default=False)),
                ('date_of_payment', models.DateField(auto_now_add=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('customer_email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('event', models.ForeignKey(db_column='event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event')),
            ],
        ),
    ]
