# Generated by Django 4.1.2 on 2023-03-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rem_riders_created',
            field=models.DateTimeField(blank=True, default='01.01.2010', null=True),
        ),
    ]
