# Generated by Django 4.0.4 on 2022-04-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='customer_email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
