# Generated by Django 4.0.4 on 2022-04-30 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(db_column='event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event'),
        ),
    ]
