# Generated by Django 4.0.4 on 2022-05-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_bem_backup_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bem_backup_2',
            field=models.FileField(blank=True, null=True, upload_to='bem_backup/'),
        ),
        migrations.AddField(
            model_name='event',
            name='bem_backup_2_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
