# Generated by Django 4.0.4 on 2022-04-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_entry_customer_email_entry_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='logout',
            new_name='checkout',
        ),
    ]
