# Generated by Django 4.2 on 2023-05-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_event_rem_riders_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ec_file",
            field=models.FileField(blank=True, null=True, upload_to="ec-files"),
        ),
        migrations.AddField(
            model_name="event",
            name="ec_file_uploaded",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="rem_riders_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
