# Generated by Django 4.0.3 on 2022-04-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_entryclasses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reg_open_to',
            field=models.DateTimeField(default='2021-12-31'),
        ),
    ]
