# Generated by Django 4.0.3 on 2022-04-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_entryclasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.entryclasses'),
        ),
    ]
