# Generated by Django 4.0.4 on 2022-05-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_entry_class_20_alter_entry_class_24'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryforeign',
            options={'verbose_name': 'Registrace zahraničních jezdců', 'verbose_name_plural': 'Registrace zahraničních jezdců'},
        ),
    ]
