# Generated by Django 3.1.7 on 2021-03-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='place',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='rider',
            field=models.IntegerField(default=0),
        ),
    ]
