# Generated by Django 4.0.4 on 2022-05-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_bem_backup_2_event_bem_backup_2_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bem_backup_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bem_backup_2_uploaded',
        ),
    ]
