# Generated by Django 4.2 on 2023-05-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_event_ec_file_event_ec_file_uploaded_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="ec_file_uploaded", new_name="ec_file_created",
        ),
        migrations.AlterField(
            model_name="event",
            name="ec_file",
            field=models.FileField(blank=True, null=True, upload_to="ec-files/"),
        ),
    ]
