# Generated by Django 4.0.3 on 2022-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_reg_open_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reg_open_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
