# Generated by Django 4.0.4 on 2022-05-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_entryforeign_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForeignEntry',
        ),
    ]
