# Generated by Django 3.1.7 on 2021-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210319_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Závod', 'verbose_name_plural': 'Závody'},
        ),
        migrations.AddField(
            model_name='result',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
