# Generated by Django 4.0.3 on 2022-04-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_event_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_classes',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='event.entryclasses'),
        ),
    ]
