# Generated by Django 4.2 on 2023-05-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_rename_ec_file_uploaded_event_ec_file_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ec_insurance_file",
            field=models.FileField(blank=True, null=True, upload_to="ec-files/"),
        ),
        migrations.AddField(
            model_name="event",
            name="ec_insurance_file_created",
            field=models.FileField(blank=True, null=True, upload_to="ec-files/"),
        ),
    ]
