# Generated by Django 3.1.7 on 2021-03-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210319_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Mistrovství ČR', 'Mistrovství ČR'), ('Český pohár', 'Český pohár'), ('Česká liga', 'Česlá liga'), ('Moravská liga', 'Moravská liga'), ('Volný závod', 'Volný závod')], default='Volný závod', max_length=100),
        ),
    ]
