# Generated by Django 4.0.4 on 2022-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_bem_backup_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bem_backup_2_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
