# Generated by Django 4.2 on 2023-05-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_event_ec_insurance_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ec_insurance_file_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
