# Generated by Django 4.0.3 on 2022-04-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_event_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='classes_code',
        ),
    ]
