# Generated by Django 4.0.3 on 2022-04-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_classes_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_classes',
            new_name='classes_in_event',
        ),
    ]
