# Generated by Django 4.1.2 on 2023-03-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_bem_backup_2_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rem_entries',
            field=models.FileField(blank=True, null=True, upload_to='rem_entries/'),
        ),
        migrations.AddField(
            model_name='event',
            name='rem_entries_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='bem_riders_list',
            field=models.FileField(blank=True, null=True, upload_to='rem_riders/'),
        ),
    ]
