# Generated by Django 4.1.2 on 2023-05-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0034_rename_world_plate_20_rider_plate_champ_20_and_more'),
        ('event', '0007_alter_entry_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rider',
            field=models.ForeignKey(db_column='rider', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rider.rider', to_field='uci_id'),
        ),
    ]
