# Generated by Django 4.0.3 on 2022-04-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_event_classes_event_classes_in_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='classes_in_event',
            new_name='classes_and_fees_like',
        ),
    ]
