# Generated by Django 3.1.7 on 2021-03-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210318_1117'),
        ('event', '0007_auto_20210319_1855'),
    ]

    operations = [
    ]
