# Generated by Django 4.0.3 on 2022-04-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_classes_in_event_event_classes_and_fees_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='type_for_ranking',
        ),
    ]
