# Generated by Django 3.1.7 on 2021-03-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_merge_20210319_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Závod', 'verbose_name_plural': 'Závody'},
        ),
    ]
