# Generated by Django 3.1.7 on 2021-04-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20210319_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
