# Generated by Django 4.0.3 on 2022-04-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_rename_type_event_type_for_ranking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryclasses',
            options={'verbose_name': 'Kategorie a startovné', 'verbose_name_plural': 'Kategorie a startovné'},
        ),
        migrations.AddField(
            model_name='entryclasses',
            name='boys_8_fee',
            field=models.IntegerField(default=0),
        ),
    ]
