# Generated by Django 4.0.3 on 2022-04-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_xml_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bem_backup_path',
            field=models.FileField(blank=True, null=True, upload_to='bem_backup/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bem_entries',
            field=models.FileField(blank=True, null=True, upload_to='bem_entries/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bem_riders_list',
            field=models.FileField(blank=True, null=True, upload_to='bem_riders/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fast_riders_path',
            field=models.FileField(blank=True, null=True, upload_to='full_results/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='full_results_path',
            field=models.FileField(blank=True, null=True, upload_to='full_results/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='proposition_path',
            field=models.FileField(blank=True, null=True, upload_to='propositions/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='series_path',
            field=models.FileField(blank=True, null=True, upload_to='series/'),
        ),
    ]
