# Generated by Django 3.2.12 on 2022-04-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissar', '0002_auto_20220416_1044'),
        ('event', '0010_alter_entryclasses_options_entryclasses_boys_8_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='classes_and_fees_like',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.SET_DEFAULT, to='event.entryclasses'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PCP', to='commissar.commissar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pcp_assist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PCP_asist', to='commissar.commissar'),
        ),
    ]
