# Generated by Django 3.1.7 on 2021-04-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20210403_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='is_20',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='result',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
