# Generated by Django 4.2.1 on 2023-05-21 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0035_rider_fix_valid_licence'),
        ('event', '0011_alter_entry_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rider',
            field=models.ForeignKey(db_column='rider', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rider.rider'),
        ),
    ]
