# Generated by Django 4.0.3 on 2022-04-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_rename_full_results_path_event_full_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='bem_backup_path',
            new_name='bem_backup',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='fast_riders_path',
            new_name='fast_riders',
        ),
    ]
