# Generated by Django 3.2.12 on 2022-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_event_type_for_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='results_path_to_file',
            new_name='fast_riders_path',
        ),
        migrations.AddField(
            model_name='event',
            name='fast_riders_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='results_path_path',
            field=models.FileField(blank=True, null=True, upload_to='static/results'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_for_ranking',
            field=models.CharField(choices=[('Mistrovství ČR jednotlivců', 'Mistrovství ČR jednotlivců'), ('Mistrovství ČR družstev', 'Mistrovství ČR družstev'), ('Český pohár', 'Český pohár'), ('Česká liga', 'Česká liga'), ('Moravská liga', 'Moravská liga'), ('Volný závod', 'Volný závod'), ('Nebodovaný závod', 'Nebodovaný závod'), ('Evropský pohár', 'Evropský pohár'), ('Mistrovství Evropy', 'Mistrovství Evropy'), ('Mistrovství světa', 'Mistrovství světa')], default='Volný závod', max_length=100),
        ),
    ]
