# Generated by Django 3.2.12 on 2022-04-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20220418_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fast_riders_path',
            field=models.FileField(blank=True, null=True, upload_to='static/full_results'),
        ),
    ]
