# Generated by Django 3.2.12 on 2022-04-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_event_fast_riders_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='results_path_path',
        ),
        migrations.AddField(
            model_name='event',
            name='results_path',
            field=models.FileField(blank=True, null=True, upload_to='static/full_results'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fast_riders_path',
            field=models.FileField(blank=True, null=True, upload_to='static/results'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fast_riders_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='results_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
