# Generated by Django 4.2.6 on 2023-10-22 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rider', '0035_rider_fix_valid_licence'),
        ('event', '0016_rename_xml_results_uploaded_event_xls_results_uploaded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_20', models.BooleanField(default=False)),
                ('is_24', models.BooleanField(default=False)),
                ('class_20', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('class_24', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fee_20', models.IntegerField(blank=True, default=0, null=True)),
                ('fee_24', models.IntegerField(blank=True, default=0, null=True)),
                ('stripe_payload', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rider.rider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nákupní košík závodu',
                'verbose_name_plural': 'Nákupní košík závodů',
            },
        ),
    ]
