# Generated by Django 3.2.12 on 2022-04-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20220418_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fast_riders_path',
            field=models.FileField(blank=True, null=True, upload_to='static/full_results'),
        ),
        migrations.AddField(
            model_name='event',
            name='fast_riders_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
