# Generated by Django 4.2.6 on 2023-10-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_remove_result_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryclasses',
            name='beginners_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entryclasses',
            name='beginners_1_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entryclasses',
            name='beginners_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entryclasses',
            name='beginners_2_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entryclasses',
            name='beginners_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entryclasses',
            name='beginners_3_fee',
            field=models.IntegerField(default=0),
        ),
    ]
