# Generated by Django 3.1.7 on 2021-04-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_result_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='fee_boys_girls',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='event',
            name='fee_cruiser',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='event',
            name='fee_elite',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='event',
            name='fee_junior',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='event',
            name='fee_men_women',
            field=models.IntegerField(default=300),
        ),
    ]
