# Generated by Django 3.2 on 2021-04-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20210406_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_uci_race',
            field=models.BooleanField(default=False),
        ),
    ]
