# Generated by Django 3.2.12 on 2022-04-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_event_xml_results_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commission_fee',
            field=models.IntegerField(default=0),
        ),
    ]
