# Generated by Django 3.2 on 2021-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_event_is_uci_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pcp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pcp_asist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
