# Generated by Django 4.2.6 on 2023-10-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_order_class_beginner_order_fee_beginner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_beinner',
            new_name='is_beginner',
        ),
    ]
