# Generated by Django 3.2.12 on 2022-04-18 23:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_event_commission_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='prices',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeschedule',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
    ]
