# Generated by Django 3.2 on 2021-04-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_auto_20210407_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='pcp_asist',
            new_name='pcp_assist',
        ),
    ]
