# Generated by Django 4.2.6 on 2023-11-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_alter_entry_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reg_open_from',
            field=models.DateTimeField(default='2021-04-01 00:00:00'),
        ),
    ]
