# Generated by Django 3.2.12 on 2022-04-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20220419_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='double_race',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_for_ranking',
            field=models.CharField(choices=[('Mistrovství ČR jednotlivců', 'Mistrovství ČR jednotlivců'), ('Mistrovství ČR družstev', 'Mistrovství ČR družstev'), ('Český pohár', 'Český pohár'), ('Česká liga', 'Česká liga'), ('Moravská liga', 'Moravská liga'), ('Volný závod', 'Volný závod'), ('Evropský pohár', 'Evropský pohár'), ('Mistrovství Evropy', 'Mistrovství Evropy'), ('Mistrovství světa', 'Mistrovství světa'), ('Nebodovaný závod', 'Nebodovaný závod')], default='Volný závod', max_length=100),
        ),
    ]
