# Generated by Django 3.2 on 2021-04-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_rename_pcp_asist_event_pcp_assist'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='class_20',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='class_24',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_20',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_24',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='rider',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='transaction_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
