# Generated by Django 4.2.6 on 2023-11-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0037_alter_rider_class_beginner'),
        ('event', '0025_alter_event_reg_open_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rider',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rider.rider'),
        ),
    ]
