# Generated by Django 3.2 on 2021-04-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_auto_20210409_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='payment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
