# Generated by Django 4.0.3 on 2022-04-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_auto_20220419_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timeschedule',
        ),
        migrations.AddField(
            model_name='event',
            name='bem_backup_path',
            field=models.FileField(blank=True, null=True, upload_to='static/bem_backup'),
        ),
        migrations.AddField(
            model_name='event',
            name='bem_backup_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='proposition_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='proposition_path',
            field=models.FileField(blank=True, null=True, upload_to='static/propositions'),
        ),
    ]
