# Generated by Django 3.2.12 on 2022-04-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_remove_event_notes_remove_event_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='series_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='series_path',
            field=models.FileField(blank=True, null=True, upload_to='static/series'),
        ),
    ]
