# Generated by Django 4.2.6 on 2023-11-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_entry_user_alter_entry_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
