# Generated by Django 3.2 on 2021-04-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_entry_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='event',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
