# Generated by Django 4.2.6 on 2023-11-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_alter_entry_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
