# Generated by Django 3.2 on 2021-04-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_alter_entry_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='logout',
            field=models.BooleanField(default=False),
        ),
    ]
