# Generated by Django 3.2 on 2021-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_entry_logout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='registration_open',
            new_name='reg_open',
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='prices',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='reg_open_from',
            field=models.DateField(default='2021-05-01'),
        ),
        migrations.AddField(
            model_name='event',
            name='reg_open_to',
            field=models.DateField(default='2021-12-31'),
        ),
        migrations.AddField(
            model_name='event',
            name='system',
            field=models.CharField(choices=[('3 základní rozjíždky a KO system', '3 základní rozjíždky a KO system'), ('5 základních rozjíždek a KO system', '5 základních rozjíždek a KO system')], default='3 základní rozjíždky a KO system', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='timeschedule',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
