# Generated by Django 4.2.6 on 2023-11-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_entry_created_entry_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='confirmed',
        ),
    ]
