# Generated by Django 3.2 on 2021-04-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_auto_20210411_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
