# Generated by Django 3.2 on 2021-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_event_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Mistrovství ČR jednotlivců', 'Mistrovství ČR jednotlivců'), ('Mistrovství ČR družstev', 'Mistrovství ČR družstev'), ('Český pohár', 'Český pohár'), ('Česká liga', 'Česká liga'), ('Moravská liga', 'Moravská liga'), ('Volný závod', 'Volný závod'), ('Nebodovaný závod', 'Nebodovaný závod'), ('Mezinárodní závod', 'Mezinárodní závod')], default='Volný závod', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='prices',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='system',
            field=models.CharField(blank=True, choices=[('3 základní rozjíždky a KO system', '3 základní rozjíždky a KO system'), ('5 základních rozjíždek a KO system', '5 základních rozjíždek a KO system')], default='3 základní rozjíždky a KO system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeschedule',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
