# Generated by Django 3.2 on 2021-04-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_auto_20210411_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Závod', 'verbose_name_plural': 'Závody'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='reg_open',
        ),
        migrations.AddField(
            model_name='entry',
            name='fee_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='fee_24',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
