# Generated by Django 4.2.6 on 2024-03-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_rename_cr_men_40_49_entryclasses_cr_men_40_44_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_of_insurance',
            field=models.IntegerField(default=0),
        ),
    ]
