# Generated by Django 5.0.3 on 2024-04-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_event_price_of_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryclasses',
            name='beginners_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entryclasses',
            name='beginners_4_fee',
            field=models.IntegerField(default=0),
        ),
    ]
