# Generated by Django 5.0.3 on 2024-04-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0034_entryclasses_beginners_4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_beginners_race",
            field=models.BooleanField(default=False),
        ),
    ]
