# Generated by Django 3.2 on 2021-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_auto_20210413_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bem_entries',
            field=models.FileField(blank=True, null=True, upload_to='static/bem_entries'),
        ),
        migrations.AddField(
            model_name='event',
            name='bem_riders_list',
            field=models.FileField(blank=True, null=True, upload_to='static/bem_riders'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reg_open_from',
            field=models.DateField(default='2021-04-01'),
        ),
    ]
