# Generated by Django 3.2 on 2021-04-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20210413_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bem_entries_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='bem_riders_list',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
