# Generated by Django 5.0.3 on 2024-04-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0036_remove_event_is_beginners_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_beginners_race",
            field=models.BooleanField(default=False),
        ),
    ]
