# Generated by Django 3.2 on 2021-04-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_auto_20210413_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bem_riders_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='bem_riders_list',
            field=models.FileField(blank=True, null=True, upload_to='static/bem_riders'),
        ),
    ]
