# Generated by Django 5.0.3 on 2024-04-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0037_event_is_beginners_race"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="is_beginners_race",),
    ]
