# Generated by Django 3.2 on 2021-04-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_auto_20210413_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='full_results_path',
            field=models.FileField(blank=True, null=True, upload_to='static/full_results'),
        ),
        migrations.AddField(
            model_name='event',
            name='full_results_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
