# Generated by Django 3.2 on 2021-04-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_auto_20210414_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_open',
            field=models.BooleanField(default=True),
        ),
    ]
