# Generated by Django 5.0.3 on 2024-05-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0039_seasonsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seasonsettings",
            options={
                "verbose_name": "Nastavení sezony",
                "verbose_name_plural": "Nastavení sezony",
            },
        ),
    ]
