# Generated by Django 3.2 on 2021-04-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_event_classes_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fee_boys_girls',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fee_cruiser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fee_elite',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fee_junior',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fee_men_women',
        ),
    ]
