# Generated by Django 5.0.3 on 2025-02-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0041_credittransaction_debettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="debettransaction",
            name="paymant_valid",
            field=models.BooleanField(default=True),
        ),
    ]
