# Generated by Django 5.0.3 on 2025-02-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0042_debettransaction_paymant_valid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debettransaction",
            old_name="paymant_valid",
            new_name="payment_valid",
        ),
    ]
