# Generated by Django 3.2 on 2021-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_result_marked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='marked',
            new_name='marked_20',
        ),
        migrations.AddField(
            model_name='result',
            name='marked_24',
            field=models.BooleanField(default=0),
        ),
    ]
