# Generated by Django 3.2 on 2021-04-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_auto_20210417_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='type',
        ),
    ]
