# Generated by Django 5.0.3 on 2025-02-22 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_rename_paymant_valid_debettransaction_payment_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Karetní poplatek',
                'verbose_name_plural': 'Karetní poplatky',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='type_for_ranking',
            field=models.CharField(choices=[('Mistrovství ČR jednotlivců', 'Mistrovství ČR jednotlivců'), ('Mistrovství ČR družstev', 'Mistrovství ČR družstev'), ('Český pohár', 'Český pohár'), ('Česká liga', 'Česká liga'), ('Moravská liga', 'Moravská liga'), ('Volný závod', 'Volný závod'), ('Evropský pohár', 'Evropský pohár'), ('Mistrovství Evropy', 'Mistrovství Evropy'), ('Mistrovství světa', 'Mistrovství světa'), ('Světový pohár', 'Světový pohár'), ('Nebodovaný závod', 'Nebodovaný závod')], default='Volný závod', max_length=100),
        ),
    ]
