# Generated by Django 3.2.7 on 2021-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0045_rename_type_result_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
