# Generated by Django 5.0.3 on 2025-03-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_club_lng_club_lon'),
        ('event', '0046_event_html_results_event_html_results_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ccf_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='ccf_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
            },
        ),
    ]
