# Generated by Django 5.1.7 on 2025-03-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0048_result_country_result_is_beginner"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ccf_created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
