# Generated by Django 5.1.7 on 2025-03-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0049_event_ccf_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
