# Generated by Django 5.1.7 on 2025-03-25 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0050_alter_event_date"),
        ("rider", "0043_remove_foreignrider_middle_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_type", models.CharField(max_length=20)),
                ("round_number", models.IntegerField(blank=True, null=True)),
                ("gate", models.IntegerField(blank=True, null=True)),
                ("lane", models.IntegerField(blank=True, null=True)),
                ("place", models.CharField(blank=True, max_length=10, null=True)),
                ("race_points", models.IntegerField(blank=True, null=True)),
                ("moto_points", models.IntegerField(blank=True, null=True)),
                ("hill_time", models.FloatField(blank=True, null=True)),
                ("finish_time", models.FloatField(blank=True, null=True)),
                ("split_1", models.FloatField(blank=True, null=True)),
                ("split_2", models.FloatField(blank=True, null=True)),
                ("split_3", models.FloatField(blank=True, null=True)),
                ("split_4", models.FloatField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.event",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="event.result",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rider.rider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jízda závodníka",
                "verbose_name_plural": "Jízdy závodníka",
            },
        ),
    ]
