# Generated by Django 5.1.7 on 2025-03-25 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0051_racerun"),
    ]

    operations = [
        migrations.AddField(
            model_name="credittransaction",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
