# Generated by Django 5.1.7 on 2025-04-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0052_credittransaction_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="youtube_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="commission_fee",
            field=models.IntegerField(default=5),
        ),
    ]
