# Generated by Django 4.2.24 on 2025-09-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0053_event_youtube_link_alter_event_commission_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="livestream",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
