# Generated by Django 5.2.7 on 2025-10-11 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0054_event_livestream"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="classes_and_fees_like",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="event.entryclasses",
            ),
        ),
    ]
