# Generated by Django 5.2.7 on 2025-10-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissar", "0007_commissar_created_commissar_is_active_and_more"),
        ("event", "0055_alter_event_classes_and_fees_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ccf_id",
            field=models.IntegerField(default=0, help_text="ID závodu na portálu ČSC"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(help_text="Název závodu", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="pcp",
            field=models.ForeignKey(
                blank=True,
                help_text="Hlavní rozhodčí",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="PCP",
                to="commissar.commissar",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="pcp_assist",
            field=models.ForeignKey(
                blank=True,
                help_text="Asistent hlavního rozhodčího",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="PCP_asist",
                to="commissar.commissar",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="system",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "3 základní rozjíždky a KO system",
                        "3 základní rozjíždky a KO system",
                    ),
                    (
                        "5 základních rozjíždek a KO system",
                        "5 základních rozjíždek a KO system",
                    ),
                    ("LCQ", "LCQ"),
                ],
                default="3 základní rozjíždky a KO system",
                max_length=100,
                null=True,
            ),
        ),
    ]
