# Generated by Django 5.2.7 on 2025-10-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0056_alter_event_ccf_id_alter_event_name_alter_event_pcp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsettings',
            name='beginners_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
