# Generated by Django 5.2.7 on 2025-11-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0057_seasonsettings_beginners_allowed_delete_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonsettings',
            old_name='best_cl',
            new_name='best_league',
        ),
        migrations.RemoveField(
            model_name='seasonsettings',
            name='best_ml',
        ),
    ]
