# Generated by Django 6.0.3 on 2026-03-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0058_rename_best_cl_seasonsettings_best_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryclasses',
            name='girls_6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entryclasses',
            name='girls_6_fee',
            field=models.IntegerField(default=0),
        ),
    ]
