# Generated by Django 6.0.3 on 2026-03-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0071_seasonsettings_trainer_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproposition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
