# Generated by Django 6.0.3 on 2026-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0077_event_commissar_role_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='uci_code_men_elite',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='UCI code men elite'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uci_code_men_junior',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='UCI code men junior'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uci_code_men_under_23',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='UCI code men under 23'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uci_code_women_elite',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='UCI code women elite'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uci_code_women_junior',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='UCI code women junior'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uci_code_women_under_23',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='UCI code women under 23'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uci_event_code',
            field=models.CharField(blank=True, default='', help_text='Unique UCI event code', max_length=64, verbose_name='UCI event code'),
        ),
    ]
