# Generated by Django 6.0.3 on 2026-03-29 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0080_normalize_entryforeign_uci_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventExportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_type', models.CharField(choices=[('results_to_ccf', 'Výsledky do ČSC')], default='results_to_ccf', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Ve frontě'), ('running', 'Zpracovává se'), ('uploading', 'Odesílá se'), ('completed', 'Dokončeno'), ('failed', 'Selhalo')], default='queued', max_length=16)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('reference_value', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_export_jobs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='event.event')),
            ],
            options={
                'verbose_name': 'Exportní úloha',
                'verbose_name_plural': 'Exportní úlohy',
                'indexes': [models.Index(fields=['event', 'job_type', 'status'], name='evt_expjob_evt_type_stat'), models.Index(fields=['created'], name='event_export_job_created')],
            },
        ),
    ]
