# Generated by Django 6.0.3 on 2026-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0085_alter_entryauditlog_action_alter_entryauditlog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='kind',
            field=models.CharField(choices=[('topup', 'Dobití kreditu'), ('checkout_refund', 'Vrácení startovného po checkoutu'), ('eshop_purchase', 'Nákup v e-shopu')], default='topup', max_length=32),
        ),
    ]
