# Generated by Django 6.0.3 on 2026-05-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0081_eventexportjob'),
        ('event', '0092_entryforeign_user_debettransaction_foreign_entry'),
    ]

    operations = [
    ]
