# Generated by Django 6.0.3 on 2026-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0094_entryforeign_stripe_refund_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS "event_eventexportjob";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='EventExportJob',
                ),
            ],
        ),
    ]
