# Generated by Django 6.0.3 on 2026-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0094_entryforeign_stripe_refund_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventexportjob',
            name='evt_expjob_evt_type_stat',
        ),
        migrations.RemoveIndex(
            model_name='eventexportjob',
            name='event_export_job_created',
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='EventExportJob',
        ),
    ]
