# Generated by Django 6.0.3 on 2026-06-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0097_populate_mcr_club_entry_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsettings',
            name='mobile_app_monthly_price',
            field=models.IntegerField(default=99),
        ),
    ]
