# Generated by Django 6.0.3 on 2026-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0098_seasonsettings_mobile_app_monthly_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonsettings',
            name='mobile_app_monthly_price',
        ),
        migrations.AddField(
            model_name='seasonsettings',
            name='mobile_app_annual_price',
            field=models.IntegerField(default=499),
        ),
    ]
