# Generated by Django 6.0.3 on 2026-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0099_rename_mobile_app_monthly_to_annual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='kind',
            field=models.CharField(choices=[('topup', 'Dobití kreditu'), ('checkout_refund', 'Vrácení startovného po checkoutu'), ('eshop_purchase', 'Nákup v e-shopu'), ('eshop_refund', 'Storno objednávky e-shopu'), ('promo', 'Promo kód')], default='topup', max_length=32),
        ),
    ]
