# Generated by Django 6.0.3 on 2026-06-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0100_alter_credittransaction_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_for_ranking',
            field=models.CharField(choices=[('Mistrovství ČR jednotlivců', 'Mcr Jednotlivcu'), ('Mistrovství ČR družstev', 'Mcr Druzstev'), ('Český pohár', 'Cesky Pohar'), ('Česká liga', 'Ceska Liga'), ('Moravská liga', 'Moravska Liga'), ('Volný závod', 'Volny Zavod'), ('Evropský pohár', 'Evropsky Pohar'), ('Mistrovství Evropy', 'Mistrovstvi Evropy'), ('Mistrovství světa', 'Mistrovstvi Sveta'), ('Světový pohár', 'Svetovy Pohar'), ('Nebodovaný závod', 'Nebodovany Zavod')], default='Volný závod', max_length=100),
        ),
    ]
