# Generated by Django 6.0.3 on 2026-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0101_alter_event_type_for_ranking'),
        ('rider', '0057_alter_promocode_discount_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='racerun',
            index=models.Index(fields=['event', 'round_type'], name='event_racerun_evt_round'),
        ),
        migrations.AddIndex(
            model_name='racerun',
            index=models.Index(fields=['rider', 'category'], name='event_racerun_rider_cat'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['event', 'category', 'place'], name='event_result_evt_cat_place'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['rider', 'date'], name='event_result_rider_date'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['event_type', 'date'], name='event_result_evttype_date'),
        ),
    ]
