# Generated by Django 6.0.3 on 2026-08-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0103_event_event_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventControlSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('pull', 'Stažení z Event Control Admin'), ('push', 'Výdej pro Event Control Admin')], default='pull', max_length=10)),
                ('entity', models.CharField(choices=[('riders', 'Jezdci'), ('clubs', 'Kluby')], max_length=10)),
                ('source', models.CharField(default='cron', help_text='cron / command / api', max_length=64)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('dry_run', models.BooleanField(default=False)),
                ('received', models.IntegerField(default=0, help_text='Počet záznamů přijatých z centrální databáze')),
                ('matched', models.IntegerField(default=0, help_text='Spárováno s existujícím záznamem')),
                ('created', models.IntegerField(default=0, help_text='Založeno lokálně')),
                ('skipped', models.IntegerField(default=0, help_text='Přeskočeno (nekompletní data)')),
                ('conflicts', models.IntegerField(default=0, help_text='Spárováno, ale data se liší (web je master)')),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Synchronizace Event Control',
                'verbose_name_plural': 'Synchronizace Event Control',
                'ordering': ['-started'],
                'indexes': [models.Index(fields=['entity', '-started'], name='event_ecsync_entity_start')],
            },
        ),
    ]
