# Generated by Django 3.1.7 on 2021-03-16 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uci_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Muž', 'Muž'), ('Žena', 'Žena'), ('Ostatní', 'Ostatní')], max_length=10)),
                ('have_girl_bonus', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('path_to_photo', models.ImageField(blank=True, null=True, upload_to='images/riders')),
                ('is_20', models.BooleanField(default=False)),
                ('is_24', models.BooleanField(default=False)),
                ('is_elite', models.BooleanField(default=False)),
                ('transponder_20', models.CharField(blank=True, max_length=8, null=True)),
                ('transponder_24', models.CharField(blank=True, max_length=8, null=True)),
                ('plate', models.IntegerField(blank=True, default=0, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approwe', models.BooleanField(default=False)),
                ('have_valid_licence', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('approwed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_club', to='club.club')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
