# Generated by Django 3.1.7 on 2021-03-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_auto_20210316_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='path_to_photo',
            new_name='photo',
        ),
    ]
