# Generated by Django 3.1.7 on 2021-03-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_auto_20210317_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'Jezdci'},
        ),
    ]
