# Generated by Django 3.1.7 on 2021-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_auto_20210318_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='class_20',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rider',
            name='class_24',
            field=models.CharField(default='', max_length=50),
        ),
    ]
