# Generated by Django 3.1.7 on 2021-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0006_auto_20210319_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='class_20',
            field=models.CharField(choices=[('B6', 'Boys 6'), ('B7', 'Boys 7')], default='Boys 6', max_length=50),
        ),
    ]
