# Generated by Django 3.1.7 on 2021-03-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0007_auto_20210319_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='class_20',
            field=models.CharField(choices=[('Boys 6', 'Boys 6'), ('Boys 7', 'Boys 7')], default='Boys 6', max_length=50),
        ),
    ]
