# Generated by Django 3.1.7 on 2021-03-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0009_auto_20210319_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='class_24',
            field=models.CharField(choices=[('Boys 12 and under', 'Boys 12 and under'), ('Boys 13 and 14', 'Boys 13 and 14'), ('Boys 15 a 16', 'Boys 15 a 16'), ('Men 17-24', 'Men 17-27'), ('Men 25-29', 'Men 25-39'), ('Men 30-34', 'Men 30-34'), ('Men 35-39', 'Men 35-39'), ('Men 40-49', 'Men 40-49'), ('Men 50 and over', 'Men 50 and over'), ('Girls 12 and under', 'Girls 12 and under'), ('Girls 13-16', 'Girls 13-16'), ('Women 17-29', 'Women 17-29'), ('Women 30-39', 'Women 30-99'), ('Women 40 and over', 'Women 40 and over')], default='Boys 12 and under', max_length=50),
        ),
    ]
