# Generated by Django 3.1.7 on 2021-03-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0010_auto_20210319_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='is_in_representation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='is_in_talent_team',
            field=models.BooleanField(default=False),
        ),
    ]
