# Generated by Django 3.1.7 on 2021-03-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0011_auto_20210319_1814'),
        ('rider', '0005_auto_20210318_1117'),
    ]

    operations = [
    ]
