# Generated by Django 3.1.7 on 2021-03-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0012_merge_20210319_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='class_20',
            field=models.CharField(choices=[('Boys 6', 'Boys 6'), ('Boys 7', 'Boys 7'), ('Boys 8', 'Boys 8'), ('Boys 9', 'Boys 9'), ('Boys 10', 'Boys 10'), ('Boys 11', 'Boys 11'), ('Boys 12', 'Boys 12'), ('Boys 13', 'Boys 13'), ('Boys 14', 'Boys 14'), ('Boys 15', 'Boys 16'), ('Boys 17', 'Boys 17'), ('Men 17-24', 'Men 17-24'), ('Men 25-29', 'Men 25-29'), ('Men 30-34', 'Men 30-34'), ('Men 35 and over', 'Men 35 and over'), ('Girls 7', 'Girls 7'), ('Girls 8', 'Girls 8'), ('Girls 9', 'Girls 9'), ('Girls 10', 'Girls 10'), ('Girls 11', 'Girls 11'), ('Girls 12', 'Girls 12'), ('Girls 13', 'Girls 13'), ('Girls 14', 'Girls 14'), ('Girls 15', 'Girls 16'), ('Women 17-24', 'Women 17-24'), ('Women 25 and over', 'Women 25 and over')], default='Boys 6', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='class_24',
            field=models.CharField(choices=[('Boys 12 and under', 'Boys 12 and under'), ('Boys 13 and 14', 'Boys 13 and 14'), ('Boys 15 a 16', 'Boys 15 a 16'), ('Men 17-24', 'Men 17-27'), ('Men 25-29', 'Men 25-39'), ('Men 30-34', 'Men 30-34'), ('Men 35-39', 'Men 35-39'), ('Men 40-49', 'Men 40-49'), ('Men 50 and over', 'Men 50 and over'), ('Girls 12 and under', 'Girls 12 and under'), ('Girls 13-16', 'Girls 13-16'), ('Women 17-29', 'Women 17-29'), ('Women 30-39', 'Women 30-99'), ('Women 40 and over', 'Women 40 and over')], default='Boys 12 and under', max_length=50, null=True),
        ),
    ]
