# Generated by Django 3.1.7 on 2021-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0014_auto_20210327_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='plate_color_20',
            field=models.CharField(default='yellow', max_length=10, null=True),
        ),
    ]
