# Generated by Django 3.1.7 on 2021-04-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0015_auto_20210327_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='points_20',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rider',
            name='points_24',
            field=models.IntegerField(default=0),
        ),
    ]
