# Generated by Django 3.1.7 on 2021-04-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0017_auto_20210404_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='ranking_20',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='ranking_24',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
