# Generated by Django 3.1.7 on 2021-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0018_auto_20210405_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='ranking_24',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
