# Generated by Django 3.2 on 2021-04-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0019_auto_20210405_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/riders/uni.jpeg', null=True, upload_to='static/images/riders/'),
        ),
    ]
