# Generated by Django 3.2 on 2021-04-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0021_alter_rider_class_20'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='approwed_by',
        ),
    ]
