# Generated by Django 3.2.7 on 2021-10-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0023_auto_20210423_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
