# Generated by Django 4.0.3 on 2022-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0024_rider_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='two_years_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
