# Generated by Django 4.0.3 on 2022-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0025_rider_two_years_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
