# Generated by Django 4.0.3 on 2022-04-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0026_rider_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uci_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Muž', 'Muž'), ('Žena', 'Žena'), ('Ostatní', 'Ostatní')], max_length=10)),
                ('class_20', models.CharField(choices=[('Boys 6', 'Boys 6'), ('Boys 7', 'Boys 7'), ('Boys 8', 'Boys 8'), ('Boys 9', 'Boys 9'), ('Boys 10', 'Boys 10'), ('Boys 11', 'Boys 11'), ('Boys 12', 'Boys 12'), ('Boys 13', 'Boys 13'), ('Boys 14', 'Boys 14'), ('Boys 15', 'Boys 15'), ('Boys 16', 'Boys 16'), ('Men 17-24', 'Men 17-24'), ('Men 25-29', 'Men 25-29'), ('Men 30-34', 'Men 30-34'), ('Men 35 and over', 'Men 35 and over'), ('Girls 7', 'Girls 7'), ('Girls 8', 'Girls 8'), ('Girls 9', 'Girls 9'), ('Girls 10', 'Girls 10'), ('Girls 11', 'Girls 11'), ('Girls 12', 'Girls 12'), ('Girls 13', 'Girls 13'), ('Girls 14', 'Girls 14'), ('Girls 15', 'Girls 15'), ('Girls 16', 'Girls 16'), ('Women 17-24', 'Women 17-24'), ('Women 25 and over', 'Women 25 and over'), ('Men Junior', 'Men Junior'), ('Men Under 23', 'Men Under 23'), ('Men Elite', 'Men Elite'), ('Women Junior', 'Women Junior'), ('Women Under 23', 'Women Under 23'), ('Women Elite', 'Women Elite')], default='Boys 6', max_length=50, null=True)),
                ('class_24', models.CharField(choices=[('Boys 12 and under', 'Boys 12 and under'), ('Boys 13 and 14', 'Boys 13 and 14'), ('Boys 15 and 16', 'Boys 15 and 16'), ('Men 17-24', 'Men 17-24'), ('Men 25-29', 'Men 25-39'), ('Men 30-34', 'Men 30-34'), ('Men 35-39', 'Men 35-39'), ('Men 40-49', 'Men 40-49'), ('Men 50 and over', 'Men 50 and over'), ('Girls 12 and under', 'Girls 12 and under'), ('Girls 13-16', 'Girls 13-16'), ('Women 17-29', 'Women 17-29'), ('Women 30-39', 'Women 30-99'), ('Women 40 and over', 'Women 40 and over')], default='Boys 12 and under', max_length=50, null=True)),
                ('is_20', models.BooleanField(default=False)),
                ('is_24', models.BooleanField(default=False)),
                ('is_elite', models.BooleanField(default=False)),
                ('transponder_20', models.CharField(blank=True, max_length=8, null=True)),
                ('transponder_24', models.CharField(blank=True, max_length=8, null=True)),
                ('plate', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Zahranicni jezdec',
                'verbose_name_plural': 'Zahranicni jezdci',
                'db_table': 'Zahranicni_jezdci',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
