# Generated by Django 4.0.3 on 2022-04-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0027_foreignrider'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignrider',
            name='club',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='foreignrider',
            name='state',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
