# Generated by Django 3.2.12 on 2022-04-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0028_foreignrider_club_foreignrider_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='city',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='rc',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='street',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='zip',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
