# Generated by Django 4.0.3 on 2022-04-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0029_auto_20220419_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='photo',
            field=models.ImageField(blank=True, default='images/riders/uni.jpeg', null=True, upload_to='images/riders/'),
        ),
    ]
