# Generated by Django 3.2.12 on 2022-04-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0030_alter_rider_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='have_valid_licence',
            new_name='valid_licence',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='two_years_inactive',
        ),
    ]
