# Generated by Django 4.0.4 on 2023-03-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0032_rider_world_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='world_plate',
            new_name='world_plate_20',
        ),
        migrations.AddField(
            model_name='rider',
            name='world_plate_24',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
