# Generated by Django 4.2.1 on 2023-05-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0034_rename_world_plate_20_rider_plate_champ_20_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="fix_valid_licence",
            field=models.BooleanField(default=False),
        ),
    ]
