# Generated by Django 4.2.6 on 2023-10-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0035_rider_fix_valid_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='class_beginner',
            field=models.CharField(choices=[('Beginners 1', 'Beginners 1'), ('Beginners 2', 'Beginners 2'), ('Beginners 3', 'Beginners 3')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foreignrider',
            name='class_24',
            field=models.CharField(choices=[('Boys 12 and under', 'Boys 12 and under'), ('Boys 13 and 14', 'Boys 13 and 14'), ('Boys 15 and 16', 'Boys 15 and 16'), ('Men 17-24', 'Men 17-24'), ('Men 25-29', 'Men 25-39'), ('Men 30-34', 'Men 30-34'), ('Men 35-39', 'Men 35-39'), ('Men 40-44', 'Men 40-44'), ('Men 45-49', 'Men 45-49'), ('Men 50 and over', 'Men 50 and over'), ('Girls 12 and under', 'Girls 12 and under'), ('Girls 13-16', 'Girls 13-16'), ('Women 17-29', 'Women 17-29'), ('Women 30-39', 'Women 30-99'), ('Women 40 and over', 'Women 40 and over')], default='Boys 12 and under', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='class_24',
            field=models.CharField(choices=[('Boys 12 and under', 'Boys 12 and under'), ('Boys 13 and 14', 'Boys 13 and 14'), ('Boys 15 and 16', 'Boys 15 and 16'), ('Men 17-24', 'Men 17-24'), ('Men 25-29', 'Men 25-39'), ('Men 30-34', 'Men 30-34'), ('Men 35-39', 'Men 35-39'), ('Men 40-44', 'Men 40-44'), ('Men 45-49', 'Men 45-49'), ('Men 50 and over', 'Men 50 and over'), ('Girls 12 and under', 'Girls 12 and under'), ('Girls 13-16', 'Girls 13-16'), ('Women 17-29', 'Women 17-29'), ('Women 30-39', 'Women 30-99'), ('Women 40 and over', 'Women 40 and over')], default='Boys 12 and under', max_length=50, null=True),
        ),
    ]
