# Generated by Django 4.2.6 on 2023-10-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0036_rider_class_beginner_alter_foreignrider_class_24_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='class_beginner',
            field=models.CharField(choices=[('Beginners 1', 'Beginners 1'), ('Beginners 2', 'Beginners 2'), ('Beginners 3', 'Beginners 3'), ('', '')], default='', max_length=50, null=True),
        ),
    ]
