# Generated by Django 4.2.6 on 2024-03-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0038_alter_rider_class_beginner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='have_valid_insurance',
            field=models.BooleanField(default=False),
        ),
    ]
