# Generated by Django 5.0.3 on 2024-04-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0039_rider_have_valid_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='class_beginner',
            field=models.CharField(blank=True, choices=[('Beginners 1', 'Beginners 1'), ('Beginners 2', 'Beginners 2'), ('Beginners 3', 'Beginners 3'), ('Beginners 4', 'Beginners 4')], default='Beginners 4', max_length=50, null=True),
        ),
    ]
