# Generated by Django 5.0.3 on 2024-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0040_alter_rider_class_beginner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='nationality',
            field=models.CharField(default='CZE', max_length=3),
        ),
    ]
