# Generated by Django 5.0.3 on 2024-05-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0041_rider_nationality"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="is_qualify_to_cn_20",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rider",
            name="is_qualify_to_cn_24",
            field=models.BooleanField(default=False),
        ),
    ]
