# Generated by Django 5.0.3 on 2025-03-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0042_rider_is_qualify_to_cn_20_rider_is_qualify_to_cn_24"),
    ]

    operations = [
        migrations.RemoveField(model_name="foreignrider", name="middle_name",),
        migrations.AddField(
            model_name="foreignrider",
            name="nationality",
            field=models.CharField(default="", max_length=3),
        ),
    ]
