# Generated by Django 5.2.7 on 2025-10-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0043_remove_foreignrider_middle_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rider", old_name="is_approwe", new_name="is_approved",
        ),
    ]
