# Generated by Django 5.2.7 on 2025-10-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0044_rename_is_approwe_rider_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="points_20",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="rider",
            name="points_24",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="rider",
            name="ranking_20",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="rider",
            name="ranking_24",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
