# Generated by Django 6.0.3 on 2026-03-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0045_alter_rider_points_20_alter_rider_points_24_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignrider',
            name='class_20',
            field=models.CharField(choices=[('Boys 6', 'Boys 6'), ('Boys 7', 'Boys 7'), ('Boys 8', 'Boys 8'), ('Boys 9', 'Boys 9'), ('Boys 10', 'Boys 10'), ('Boys 11', 'Boys 11'), ('Boys 12', 'Boys 12'), ('Boys 13', 'Boys 13'), ('Boys 14', 'Boys 14'), ('Boys 15', 'Boys 15'), ('Boys 16', 'Boys 16'), ('Men 17-24', 'Men 17-24'), ('Men 25-29', 'Men 25-29'), ('Men 30-34', 'Men 30-34'), ('Men 35 and over', 'Men 35 and over'), ('Girls 6', 'Girls 6'), ('Girls 7', 'Girls 7'), ('Girls 8', 'Girls 8'), ('Girls 9', 'Girls 9'), ('Girls 10', 'Girls 10'), ('Girls 11', 'Girls 11'), ('Girls 12', 'Girls 12'), ('Girls 13', 'Girls 13'), ('Girls 14', 'Girls 14'), ('Girls 15', 'Girls 15'), ('Girls 16', 'Girls 16'), ('Women 17-24', 'Women 17-24'), ('Women 25 and over', 'Women 25 and over'), ('Men Junior', 'Men Junior'), ('Men Under 23', 'Men Under 23'), ('Men Elite', 'Men Elite'), ('Women Junior', 'Women Junior'), ('Women Under 23', 'Women Under 23'), ('Women Elite', 'Women Elite')], default='Boys 6', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='class_20',
            field=models.CharField(choices=[('Boys 6', 'Boys 6'), ('Boys 7', 'Boys 7'), ('Boys 8', 'Boys 8'), ('Boys 9', 'Boys 9'), ('Boys 10', 'Boys 10'), ('Boys 11', 'Boys 11'), ('Boys 12', 'Boys 12'), ('Boys 13', 'Boys 13'), ('Boys 14', 'Boys 14'), ('Boys 15', 'Boys 15'), ('Boys 16', 'Boys 16'), ('Men 17-24', 'Men 17-24'), ('Men 25-29', 'Men 25-29'), ('Men 30-34', 'Men 30-34'), ('Men 35 and over', 'Men 35 and over'), ('Girls 6', 'Girls 6'), ('Girls 7', 'Girls 7'), ('Girls 8', 'Girls 8'), ('Girls 9', 'Girls 9'), ('Girls 10', 'Girls 10'), ('Girls 11', 'Girls 11'), ('Girls 12', 'Girls 12'), ('Girls 13', 'Girls 13'), ('Girls 14', 'Girls 14'), ('Girls 15', 'Girls 15'), ('Girls 16', 'Girls 16'), ('Women 17-24', 'Women 17-24'), ('Women 25 and over', 'Women 25 and over'), ('Men Junior', 'Men Junior'), ('Men Under 23', 'Men Under 23'), ('Men Elite', 'Men Elite'), ('Women Junior', 'Women Junior'), ('Women Under 23', 'Women Under 23'), ('Women Elite', 'Women Elite')], default='Boys 6', max_length=50, null=True),
        ),
    ]
