# Generated by Django 6.0.3 on 2026-06-03 16:38

import django.db.models.deletion
import rider.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0098_seasonsettings_mobile_app_monthly_price'),
        ('rider', '0055_rider_mcr_wild_cards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Aktivní'), ('expired', 'Expirované'), ('canceled', 'Zrušené'), ('past_due', 'Neprodloužené')], db_index=True, default='active', max_length=20)),
                ('monthly_price', models.IntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=True)),
                ('last_renewed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_app_subscriptions', to='event.seasonsettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_app_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Předplatné mobilní aplikace',
                'verbose_name_plural': 'Předplatná mobilní aplikace',
            },
        ),
        migrations.CreateModel(
            name='MobileAppCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('reason', models.CharField(choices=[('initial', 'První aktivace'), ('renewal', 'Obnovení'), ('promo', 'Promo kód')], default='initial', max_length=20)),
                ('payment_valid', models.BooleanField(default=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_app_charges', to='event.seasonsettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_app_charges', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='rider.mobileappsubscription')),
            ],
            options={
                'verbose_name': 'Odečet za mobilní aplikaci',
                'verbose_name_plural': 'Odečty za mobilní aplikaci',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=rider.models._generate_promo_code, max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percent', 'Procento ze ceny'), ('fixed', 'Pevná sleva (Kč)'), ('free', 'Zdarma (100 %)')], default='free', max_length=10)),
                ('discount_value', models.IntegerField(default=100, help_text="Procento (0–100) nebo pevná částka v Kč. U 'Zdarma' se ignoruje.")),
                ('product', models.CharField(choices=[('mobile_app', 'Mobilní aplikace'), ('rider_stats', 'Prémiové statistiky'), ('trainer_club', 'Trenérské statistiky klubu'), ('trainer_extended', 'Rozšířené trenérské funkce'), ('all', 'Vše')], db_index=True, default='mobile_app', max_length=30)),
                ('max_uses', models.IntegerField(blank=True, help_text='Prázdné = neomezeno', null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo kód',
                'verbose_name_plural': 'Promo kódy',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('discount_applied', models.IntegerField(default=0)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='rider.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Použití promo kódu',
                'verbose_name_plural': 'Použití promo kódů',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mobileappsubscription',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='mobile_sub_user_status_exp'),
        ),
        migrations.AddConstraint(
            model_name='mobileappsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='uniq_active_mobile_app_subscription'),
        ),
        migrations.AddIndex(
            model_name='mobileappcharge',
            index=models.Index(fields=['user', 'payment_valid', 'transaction_date'], name='mobile_charge_user_valid_date'),
        ),
        migrations.AddIndex(
            model_name='mobileappcharge',
            index=models.Index(fields=['subscription'], name='mobile_charge_subscription'),
        ),
        migrations.AddConstraint(
            model_name='promocodeusage',
            constraint=models.UniqueConstraint(fields=('promo_code', 'user'), name='uniq_promo_usage_per_user'),
        ),
    ]
