# Generated by Django 6.0.3 on 2026-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0056_mobileappsubscription_mobileappcharge_promocode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Procento ze ceny'), ('fixed', 'Pevná sleva (Kč)'), ('free', 'Zdarma (100 %)'), ('credit', 'Kredit (Kč na účet)')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.IntegerField(default=100, help_text='Procento (0–100), pevná Kč sleva nebo výše kreditu v Kč.'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='product',
            field=models.CharField(choices=[('mobile_app', 'Mobilní aplikace'), ('rider_stats', 'Prémiové statistiky'), ('trainer_club', 'Trenérské statistiky klubu'), ('trainer_extended', 'Rozšířené trenérské funkce'), ('all', 'Vše'), ('credit', 'Kredit')], db_index=True, default='mobile_app', max_length=30),
        ),
    ]
