# Generated by Django 6.0.3 on 2026-08-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0057_alter_promocode_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='event_control_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ID v Event Control Admin'),
        ),
        migrations.AddField(
            model_name='rider',
            name='event_control_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Naposledy synchronizováno s Event Control Admin'),
        ),
    ]
