# Generated by Django 6.0.3 on 2026-04-17 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
                ('slug', models.SlugField(unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Pořadí')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Čeká na zpracování'), ('confirmed', 'Potvrzena'), ('shipped', 'Odesláno'), ('delivered', 'Doručeno'), ('canceled', 'Zrušena')], default='pending', max_length=16, verbose_name='Stav')),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('street', models.CharField(max_length=200, verbose_name='Ulice a č.p.')),
                ('city', models.CharField(max_length=100, verbose_name='Město')),
                ('zip_code', models.CharField(max_length=10, verbose_name='PSČ')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořena')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eshop_orders', to=settings.AUTH_USER_MODEL, verbose_name='Zákazník')),
            ],
            options={
                'verbose_name': 'Objednávka',
                'verbose_name_plural': 'Objednávky',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena (Kč)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Skladem (ks)')),
                ('image', models.ImageField(blank=True, upload_to='eshop/products/', verbose_name='Foto')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='eshop.category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['category__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Počet')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena za kus (Kč)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eshop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='eshop.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Položka objednávky',
                'verbose_name_plural': 'Položky objednávky',
            },
        ),
    ]
