# Generated by Django 6.0.3 on 2026-04-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Varianta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena (Kč)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Skladem (ks)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Pořadí')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='eshop.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Varianta produktu',
                'verbose_name_plural': 'Varianty produktu',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='eshop.productvariant', verbose_name='Varianta'),
        ),
    ]
