# Generated by Django 6.0.3 on 2026-04-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_remove_orderitem_product_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credits_charged',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Odečtené kredity'),
        ),
    ]
