# Generated by Django 6.0.3 on 2026-04-17 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_order_credits_charged'),
        ('event', '0086_alter_credittransaction_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eshop_orders', to='event.event', verbose_name='Závod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ulice a č.p.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='PSČ'),
        ),
    ]
