# Generated by Codex on 2026-04-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eshop", "0012_flexiexportsettings_orderhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("order_decrement", "Odečet objednávkou"),
                            ("cancel_return", "Vrácení po stornu"),
                            ("manual_adjustment", "Ruční úprava"),
                            ("restock", "Naskladnění"),
                        ],
                        max_length=32,
                        verbose_name="Typ pohybu",
                    ),
                ),
                ("quantity_delta", models.IntegerField(verbose_name="Změna kusů")),
                ("stock_after", models.PositiveIntegerField(verbose_name="Sklad po změně")),
                ("note", models.TextField(blank=True, verbose_name="Poznámka")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eshop_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Provedl",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="eshop.order",
                        verbose_name="Objednávka",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="eshop.productvariant",
                        verbose_name="Varianta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skladový pohyb",
                "verbose_name_plural": "Skladové pohyby",
                "ordering": ["-created", "-id"],
            },
        ),
    ]
