# Generated by Codex on 2026-04-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eshop", "0013_stockmovement"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAlertRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("note", models.TextField(blank=True, verbose_name="Poznámka")),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True, verbose_name="Vyřízeno dne")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno")),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eshop_stock_alert_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uživatel",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alert_requests",
                        to="eshop.productvariant",
                        verbose_name="Varianta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Požadavek na naskladnění",
                "verbose_name_plural": "Požadavky na naskladnění",
                "ordering": ["fulfilled_at", "-created"],
            },
        ),
    ]
