# Generated by Django 6.0.3 on 2026-06-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0015_eshoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eshopsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
