# Generated by Django 6.0.3 on 2026-10-09 06:06

from django.db import migrations, models


def mark_existing_orders_as_credit_paid(apps, schema_editor):
    """Všechny dosavadní objednávky vznikly v době plateb kredity.

    Prázdná čísla dokladů se mění na NULL: nezaplacené objednávky číslo faktury
    nemají a unikátní index by jinak nedovolil víc než jednu takovou.
    """
    Order = apps.get_model("eshop", "Order")
    Order.objects.update(payment_method="credits")
    Order.objects.filter(credits_charged__isnull=False).update(stock_deducted=True)
    Order.objects.filter(invoice_number="").update(invoice_number=None)
    Order.objects.filter(credit_note_number="").update(credit_note_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_alter_eshopsettings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zaplaceno kartou (Kč)'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zaplaceno dne'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Platbu dokončit do'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Platební karta (Stripe)'), ('credits', 'Kredity z účtu')], default='stripe', max_length=16, verbose_name='Forma úhrady'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vráceno dne'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, verbose_name='Sklad odečten'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe PaymentIntent'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe refund'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Stripe Checkout session'),
        ),
        migrations.AlterField(
            model_name='order',
            name='credit_note_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Číslo dobropisu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Číslo faktury'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Čeká na zaplacení'), ('confirmed', 'Potvrzena'), ('shipped', 'Odesláno'), ('delivered', 'Doručeno'), ('canceled', 'Zrušena')], default='pending', max_length=16, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Vytvořeno'), ('credit_charged', 'Kredit odečten'), ('payment_started', 'Platba zahájena'), ('paid', 'Zaplaceno kartou'), ('refunded', 'Platba vrácena na kartu'), ('confirmed', 'Potvrzeno'), ('invoice_issued', 'Faktura vystavena'), ('shipped', 'Odesláno'), ('delivered', 'Předáno'), ('canceled', 'Stornováno'), ('credit_refunded', 'Kredit vrácen'), ('credit_note_issued', 'Dobropis vystaven'), ('note', 'Poznámka')], max_length=32, verbose_name='Akce'),
        ),
        migrations.RunPython(mark_existing_orders_as_credit_paid, migrations.RunPython.noop),
    ]
