# Generated by Django 3.2.12 on 2022-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissar',
            name='first_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissar',
            name='last_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissar',
            name='level',
            field=models.CharField(choices=[('UCI', 'UCI'), ('ENC', 'ENC'), ('Národní', 'Národní')], default='Národní', max_length=100),
        ),
    ]
