# Generated by Django 3.2.12 on 2022-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissar', '0002_auto_20220416_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissar',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/commissar/uni.jpeg', null=True, upload_to='static/images/commissar/'),
        ),
        migrations.AlterField(
            model_name='commissar',
            name='level',
            field=models.CharField(choices=[('UCI rozhodčí', 'UCI rozhodčí'), ('Elite National Commissar', 'Elite National Commissar'), ('Národní rozhodčí', 'Národní rozhodčí'), ('', '')], default='Národní rozhodčí', max_length=100),
        ),
    ]
