# Generated by Django 3.2.12 on 2022-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissar', '0003_auto_20220417_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissar',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/users/blank-avatar-200x200.jpg', null=True, upload_to='static/images/commissar/'),
        ),
    ]
