# Generated by Django 3.2.12 on 2022-04-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissar', '0004_alter_commissar_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissar',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commissar',
            name='level',
            field=models.CharField(blank=True, choices=[('UCI rozhodčí', 'UCI rozhodčí'), ('Elite National Commissar', 'Elite National Commissar'), ('Národní rozhodčí', 'Národní rozhodčí'), ('', '')], default='Národní rozhodčí', max_length=100, null=True),
        ),
    ]
