# Generated by Django 4.0.4 on 2022-04-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissar', '0005_auto_20220419_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissar',
            name='photo',
            field=models.ImageField(blank=True, default='images/users/blank-avatar-200x200.jpg', null=True, upload_to='images/commissar/'),
        ),
    ]
