# Generated by Django 4.2.6 on 2023-10-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissar', '0006_alter_commissar_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissar',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commissar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commissar',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
