# Generated by Django 6.0.3 on 2026-05-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('race_summary', 'Shrnutí závodu'), ('rider_analysis', 'Analýza závodníka'), ('season_report', 'Sezónní zpráva'), ('custom', 'Vlastní úkol')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Čeká'), ('running', 'Spouštím'), ('done', 'Hotovo'), ('failed', 'Chyba')], default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Úkol agenta',
                'verbose_name_plural': 'Úkoly agenta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ai_agent.agenttask')),
            ],
            options={
                'verbose_name': 'Log agenta',
                'verbose_name_plural': 'Logy agenta',
                'ordering': ['created_at'],
            },
        ),
    ]
