# Generated by Django 3.1.7 on 2021-03-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name_plural': 'Kluby'},
        ),
    ]
