# Generated by Django 3.1.7 on 2021-03-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_merge_20210319_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['team_name'], 'verbose_name_plural': 'Kluby'},
        ),
    ]
