# Generated by Django 3.2 on 2021-05-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20210326_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='mapy_cz_svg',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
