# Generated by Django 3.2.7 on 2021-10-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club_mapy_cz_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
