# Generated by Django 4.2.6 on 2023-10-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20211003_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='lng',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='lon',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
