# Generated by Django 5.2.7 on 2025-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0007_club_lng_club_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="riders_in_event",
            field=models.FileField(
                blank=True, null=True, upload_to="media/riders_in_events/"
            ),
        ),
    ]
