# Generated by Django 5.2.7 on 2025-10-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0008_club_riders_in_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club", old_name="riders_in_event", new_name="riders_on_event",
        ),
    ]
