# Generated by Django 5.2.7 on 2025-10-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0009_rename_riders_in_event_club_riders_on_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club", old_name="riders_on_event", new_name="riders_on_events",
        ),
    ]
