# Generated by Codex on 2026-05-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("club", "0012_alter_club_riders_on_events"),
        ("rider", "0055_rider_mcr_wild_cards"),
    ]

    operations = [
        migrations.CreateModel(
            name="McrClubTeam",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("manager_name", models.CharField(max_length=120)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mcr_teams", to="club.club")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_mcr_club_teams", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Družstvo MČR klubů",
                "verbose_name_plural": "Družstva MČR klubů",
                "ordering": ["year", "club__team_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="McrClubTeamMember",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("wheel", models.CharField(choices=[("20", '20"'), ("24", '24"')], max_length=2)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("rider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mcr_club_team_memberships", to="rider.rider")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="members", to="club.mcrclubteam")),
            ],
            options={
                "verbose_name": "Člen družstva MČR klubů",
                "verbose_name_plural": "Členové družstva MČR klubů",
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="mcrclubteam",
            constraint=models.UniqueConstraint(fields=("year", "club", "name"), name="unique_mcr_club_team_name"),
        ),
        migrations.AddConstraint(
            model_name="mcrclubteammember",
            constraint=models.UniqueConstraint(fields=("team", "rider", "wheel"), name="unique_mcr_club_team_member_wheel"),
        ),
    ]
