# Generated by Django 6.0.3 on 2026-08-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_club_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='event_control_enabled',
            field=models.BooleanField(default=False, help_text='Povoluje stahování přihlášených jezdců přes API pro závody tohoto pořadatele.', verbose_name='BMX Event Control – přístup povolen'),
        ),
        migrations.AddField(
            model_name='club',
            name='event_control_last_access',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='BMX Event Control – poslední přístup'),
        ),
        migrations.AddField(
            model_name='club',
            name='event_control_password',
            field=models.CharField(blank=True, default='', editable=False, max_length=128, verbose_name='BMX Event Control – hash hesla'),
        ),
        migrations.AddField(
            model_name='club',
            name='event_control_password_updated',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='BMX Event Control – heslo změněno'),
        ),
        migrations.AddField(
            model_name='club',
            name='event_control_username',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='BMX Event Control – username'),
        ),
    ]
