# Generated by Django 6.0.3 on 2026-10-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_club_event_control_id_club_event_control_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.CharField(blank=True, choices=[('hlavní město Praha', 'hlavní město Praha'), ('Středočeský kraj', 'Středočeský kraj'), ('Jihočeský kraj', 'Jihočeský kraj'), ('Plzeňský kraj', 'Plzeňský kraj'), ('Karlovarský kraj', 'Karlovarský kraj'), ('Ústecký kraj', 'Ústecký kraj'), ('Liberecký kraj', 'Liberecký kraj'), ('Královéhradecký kraj', 'Královéhradecký kraj'), ('Pardubický kraj', 'Pardubický kraj'), ('Kraj Vysočina', 'Kraj Vysočina'), ('Jihomoravský kraj', 'Jihomoravský kraj'), ('Olomoucký kraj', 'Olomoucký kraj'), ('Zlínský kraj', 'Zlínský kraj'), ('Moravskoslezský kraj', 'Moravskoslezský kraj')], default='', max_length=50),
        ),
    ]
