# Generated by Django 3.1.7 on 2021-04-04 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rider', '0015_auto_20210327_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point20', models.IntegerField(default=0)),
                ('point24', models.IntegerField(default=0)),
                ('ranking20', models.IntegerField(default=0)),
                ('ranking24', models.IntegerField(default=0)),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rider.rider')),
            ],
        ),
    ]
